[versions]
binaryCompat = "0.13.0"
configuration = "0.1.0-beta01"
gradleVersions = "0.46.0"
kotlin = "1.8.10"
publish = "0.24.0"

[libraries]
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }
gradle-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradleVersions" }

[plugins]
binaryCompat = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompat" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
configuration = { id = "io.matthewnelson.kmp.configuration", version.ref = "configuration" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }
